frr defaults traditional
hostname r1
log syslog informational

router bgp 65001
 bgp router-id 1.1.1.1

 # Peer with r2 (core link)
 neighbor 10.0.0.12 remote-as 65001

 address-family ipv4 unicast
  network 10.0.0.0/24
 exit-address-family
