frr defaults traditional
hostname r2
log syslog informational

router bgp 65001
 bgp router-id 2.2.2.2

 # Core peer
 neighbor 10.0.0.11 remote-as 65001

 # Edge peer
 neighbor 10.0.1.13 remote-as 65002

 address-family ipv4 unicast
  network 10.0.0.0/24
  network 10.0.1.0/24
 exit-address-family
